### ISSUE TITLE
aframe-inspector.min.js:30 Uncaught TypeError: Cannot read property 'pause' of undefined at open (aframe-inspector.min.js:30) at HTMLScriptElement.script.onload (inspector.js:85)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#479]
Opening Inspector from A-Frame repo examples. Both with and without `INSPECTOR_VERSION=dev`. Fails using aframe-inspector repo dist as well as Inspector v0.5.2.

**Comment by ngokevin** [comment]
I got it to work once on Inspector v0.5.2, so it's a bit intermittent. Usually fails though.

**Comment by fernandojsg** [comment]
@ngokevin do you mind explaining how to reproduce it? I've tried both on the aframe.io and locally on aframe master and I can't reproduce it.

**Comment by fernandojsg** [comment]
Ok, I found that error on a-painter

**Comment by fernandojsg** [comment]
stupid bug, I believe it's already fixed by https://github.com/aframevr/aframe-inspector/commit/760796ccc6e12f9508296aae75ff084284598257
Could you verify it?

**Comment by ngokevin** [comment]
I'm still getting it. Local aframe repo, master branch, npm run dev, port 9000

**Comment by fernandojsg** [comment]
I've just tried with master branch on mac both with chrome and firefox, refreshing several times but can't reproduce it :\
![inspector2](https://user-images.githubusercontent.com/782511/27079778-69817186-5039-11e7-881f-eeaf1024f255.gif)
![inspector](https://user-images.githubusercontent.com/782511/27079779-6981fc8c-5039-11e7-8181-5aead7ec4909.gif)

Maybe you're having an issue with the cache?

**Comment by ngokevin** [comment]
Hm, doubt it. I've tried 11 days apart on different networks with hard refreshes.

![fix](https://user-images.githubusercontent.com/674727/27079886-707c05a0-4fee-11e7-9054-c0caef73b381.gif)

**Comment by ngokevin** [comment]
And Firefox `this.sceneEl is undefined`

![ff](https://user-images.githubusercontent.com/674727/27079968-c247a24a-4fee-11e7-869e-564a2c3ea834.gif)

**Comment by fernandojsg** [comment]
Poltergeist :\ I've used the same example from the text. It seems we've the same versions too. Are you on windows?

Also It seems that the error is different in your firefox and chrome, one is regarding .pause in the modules and another one is about sceneEl

![inspector3](https://user-images.githubusercontent.com/782511/27079989-4a91890e-503a-11e7-8b33-bfebc8948b74.gif)

**Comment by ngokevin** [comment]
It's the same error. `this.sceneEl is undefined` and `cannot call pause of undefined`. Trying to call `this.sceneEl.pause()`. I'm on OS X

**Comment by fernandojsg** [comment]
Could you try to use the non minified version and set a breakpoint?
I'm looking at the code and the only place where you get that call is at: https://github.com/aframevr/aframe-inspector/blob/gh-pages/src/lib/inspector.js#L310
And before calling it we've already query the `a-scene` here
https://github.com/aframevr/aframe-inspector/blob/gh-pages/src/lib/inspector.js#L28-L33
Not sure what is going on there

**Comment by fernandojsg** [comment]
@dmarcos @feiss @delapuente do you mind giving it a try? I can't find a way to reproduce it maybe you could get the same issue as kevin is having right now?

**Comment by dmarcos** [comment]
Running the inspector master:  `npm start` and visiting `http://localhost:3333/webpack-dev-server/`. does not show any errors for me. I opened / closed the inspector multiple times and tried on Firefox and Chrome. Am I trying this right?

**Comment by fernandojsg** [comment]
@dmarcos sorry I didn't expressed it correctly. You should try `aframe` master, not the inspector itself. Just test aframe master and inject the inspector there

**Comment by dmarcos** [comment]
I cannot reproduce the problem either running master inspector on aframe master examples ![bug](https://d3vv6lp55qjaqc.cloudfront.net/items/1e2h1t1N0o0t1W2F1V3t/Image%202017-06-15%20at%2012.20.47%20PM.png?X-CloudApp-Visitor-Id=bf7d229144f0f1f37ed85c0bd956bfff&v=7626d35a)

**Comment by feiss** [comment]
git clone [aframe repo]
npm install && npm run dev
opened a couple of examples, entered inspector, and I got no errors about `pause()`

**Comment by delapuente** [comment]
Same try as @feiss Everything is fine in Mac OS in both Nightly and Canary and the same in Windows. No errors regarding `pause()`.

**Comment by fernandojsg** [comment]
@feiss @dmarcos @delapuente thank you guys!

@ngokevin could you try in another computer? I've no idea what can be wrong but impossible to reproduce here either :\

**Comment by fernandojsg** [comment]
I'll close it as I can't reproduce it anywhere the same as the rest :\ If you have a way to reproduce it please reopen it again
