### ISSUE TITLE
Camera resets rotation when exiting edit mode

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#85]
After changing the camera rotation, exiting the editor into the scene resets the camera rotation to 0.

**Comment by fernandojsg** [comment]
I believe this is related to https://github.com/aframevr/aframe/issues/1685

**Comment by dmarcos** [comment]
I don't think is related. aframevr/aframe#1685 refers to the rotation reset when exiting VR mode. The editor is not affected.

**Comment by fernandojsg** [comment]
Ok thanks, so I'll take a look

**Comment by fernandojsg** [comment]
I believe it's solved by https://github.com/aframevr/aframe-inspector/pull/280 @caseyyee could you take a look?

**Comment by caseyyee** [comment]
@fernandojsg same issue still.   you can reproduce this by changing the cameras rotation, exiting the editor, and then re-entering edit.   note that the camera rotations will be reset.

**Comment by fernandojsg** [comment]
Fixed!
